steps:
  - name: 'docker:28.5.2-cli'
    entrypoint: 'sh'
    secretEnv:
      - 'DOCKER_HUB_PAT'
      - 'GITHUB_PACKAGE_REGISTRY_PAT'
    # Accessing secrets only works in the `args` field of a build step.
    args:
      - '-c'
      - >-
        echo "$${DOCKER_HUB_PAT}" | docker login --username "$${NAMESPACE}" --password-stdin "$${DOCKER_HUB_REGISTRY}";
        echo "$${GITHUB_PACKAGE_REGISTRY_PAT}" | docker login --username "$${NAMESPACE}" --password-stdin "$${GITHUB_PACKAGE_REGISTRY}"
  - name: 'docker:28.5.2-cli'
    script: |
      #!/bin/sh
      set -euo pipefail

      apk --no-cache add git make

      make stage

      if echo "${VERSION}" | grep -E -q "^[0-9]{4}-[0-9]{2}-[0-9]{2}$"; then
        # Build all combinations for a release.
        ./cicd/make-all.sh build-hpc "${VERSION}"
      else
        # Build only one combination for testing.
        make build-hpc VERSION="testing" COMPILER="gnu-11" MPI="open-mpi-5"
      fi

      docker image ls

      if echo "${VERSION}" | grep -E -q "^[0-9]{4}-[0-9]{2}-[0-9]{2}$"; then
        # Push all combinations for a release.
        ./cicd/push-all.sh push-hpc "${DOCKER_HUB_REGISTRY}" "${NAMESPACE}" "${VERSION}"
        ./cicd/push-all.sh push-hpc "${GITHUB_PACKAGE_REGISTRY}" "${NAMESPACE}" "${VERSION}"

        ./cicd/push-all.sh push-hpc-latest "${DOCKER_HUB_REGISTRY}" "${NAMESPACE}" "${VERSION}"
        ./cicd/push-all.sh push-hpc-latest "${GITHUB_PACKAGE_REGISTRY}" "${NAMESPACE}" "${VERSION}"
      else
        # Push only one combination for testing.
        make push-hpc REGISTRY="${DOCKER_HUB_REGISTRY}" NAMESPACE="${NAMESPACE}" VERSION="testing" COMPILER="gnu-11" MPI="open-mpi-5"
        make push-hpc REGISTRY="${GITHUB_PACKAGE_REGISTRY}" NAMESPACE="${NAMESPACE}" VERSION="testing" COMPILER="gnu-11" MPI="open-mpi-5"
      fi

      docker image ls
  - name: 'docker:28.5.2-cli'
    entrypoint: 'sh'
    args:
      - '-c'
      - >-
        docker logout "$${DOCKER_HUB_REGISTRY}";
        docker logout "$${GITHUB_PACKAGE_REGISTRY}"
availableSecrets:
  secretManager:
    - versionName: 'projects/${PROJECT_ID}/secrets/docker-hub-pat/versions/latest'
      env: 'DOCKER_HUB_PAT'
    - versionName: 'projects/${PROJECT_ID}/secrets/github-package-registry-pat/versions/latest'
      env: 'GITHUB_PACKAGE_REGISTRY_PAT'
options:
  env:
    - 'DOCKER_HUB_REGISTRY=docker.io'
    - 'GITHUB_PACKAGE_REGISTRY=ghcr.io'
    - 'NAMESPACE=kuanchihwang'
    - 'VERSION=${REF_NAME}'
  logging: 'CLOUD_LOGGING_ONLY'
  pool:
    name: 'projects/${PROJECT_ID}/locations/${LOCATION}/workerPools/cloud-builder-pool'
queueTtl: '3600s'
timeout: '43200s'
